### ISSUE TITLE
Release/tag?

### ISSUE THREAD

**Issue by devrimgunduz** [okbob/pgmeminfo#3]
Hi @okbob ,

Can you please release a version so that I can RPMify it?

Thanks!

**Comment by okbob** [comment]
Hi Devrim

done

pá 9. 2. 2024 v 14:49 odesílatel Devrim Gündüz ***@***.***>
napsal:

**Comment by okbob** [comment]
now I released 1.0.0

**Comment by devrimgunduz** [comment]
Thank you! RPMs are out.

BTW, for the next version it will be really more convenient for me if you do 1.0.1 (or whatever) instead of 1_0_1 :)
